[package]
name = "quake-util"
version = "0.1.0"
authors = ["Seth <rader.seth@gmail.com>"]
edition = "2021"
license = "CC0-1.0 OR MIT"

[features]
default = ["std"]
alloc_fills = ["hashbrown", "cstr_core"]
std = []

[dependencies]
hashbrown = { version = "^0.12", optional = true }
cstr_core = { version = "^0.2", optional = true, features = ["alloc"] }

[dev-dependencies]
benchmarking = "^0.4"
